# Generated by Django 5.0.14 on 2026-09-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_category'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['employee', 'area_manager']), ('area__isnull', True), _negated=True), name='user_area_required_for_employee_and_area_manager'),
        ),
    ]
