# Generated by Django 5.0.14 on 2026-09-19 04:38

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.TicketFlowUserManager()),
            ],
        ),
    ]
