# Generated by Django 5.0.14 on 2026-09-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('IN_PROCESS', 'En proceso'), ('RESOLVED', 'Resuelto')], max_length=20, null=True),
        ),
    ]
